[package]
name = "mnist-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.17.2"
ndarray-rand = "0.16.0"
mnist = "0.6"  # Handles MNIST parsing
indicatif = "0.17"  # Progress bars (like tqdm)
